[versions]
agp = "8.5.0"
coilCompose = "2.7.0"
datastorePreferences = "1.1.4"
foundation = "1.7.8"
hiltAndroid = "2.48"
hiltNavigationCompose = "1.2.0"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.2"
activityCompose = "1.9.0"
composeBom = "2024.04.01"
ksp = "1.9.0-1.0.13"
runtime = "1.7.8"
runtimeLivedata = "1.7.8"
roomRuntime = "2.6.1"
securityCrypto = "1.1.0-alpha06"
material3 = "1.3.2"
retrofit = "2.9.0"
kotlinxCoroutinesAndroid = "1.7.3"
okhttp3 = "4.9.0"
navigationCompose = "2.8.9"
cameraX = "1.4.2"
mlkitBarcode = "17.3.0"
cameraMlkitVision = "1.4.2"
serializationJson = "1.6.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3"}

androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-security-crypto = {module = "androidx.security:security-crypto", version.ref = "securityCrypto"}
androidx-compose-material3 = {module = "androidx.compose.material3:material3", version.ref="material3"}

com-squareup-retrofit2-retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
com-squareup-retrofit2-converter-gson = {module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}
com-squareup-okhttp3-okhttp = {module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3"}

org-jetbrains-kotlinx-kotlinx-coroutines-android = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid"}

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

androidx-camera-camera-core = {module = "androidx.camera:camera-core", version.ref = "cameraX"}
androidx-camera-camera-camera2 = {module = "androidx.camera:camera-camera2", version.ref = "cameraX"}
androidx-camera-camera-lifecycle = {module = "androidx.camera:camera-lifecycle", version.ref = "cameraX"}
androidx-camera-camera-view = {module = "androidx.camera:camera-view", version.ref = "cameraX"}
com-google-mlkit-barcode-scanning = {module="com.google.mlkit:barcode-scanning", version.ref = "mlkitBarcode"}
androidx-camera-mlkit-vision = { group = "androidx.camera", name = "camera-mlkit-vision", version.ref = "cameraMlkitVision" }

kotlinx-serialization-json = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson"}
kotlinx-serialization-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serializationJson"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

devtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp"}

